version: "3.1"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgresUser
      POSTGRES_PASSWORD: CHANGEME
      POSTGRES_DB: obs_gm_overlay
    ports:
      - 5432:5432
    volumes:
      - ./local-db:/var/lib/postgresql/data
