#import "./EncounterFragment.gql"
#import "./PlayerFragment.gql"

fragment Campaign on Campaign {
	id
	name
	gmInspiration
	cooldownType
	cooldownTime
	lastInspirationUsed
	players {
		...Player
	}
	activeEncounter {
		...Encounter
	}
}
