#import "./InitiativeFragment.gql"
#import "./NpcFragment.gql"
#import "./PlayerFragment.gql"

fragment Campaign on Campaign {
	id
	name
	gmInspiration
	cooldownType
	cooldownTime
	lastInspirationUsed
	hideNpcNames
	players {
		...Player
	}
	npcs {
		...NPC
	}
	...Initiative
}
