import type { NextPage } from "next";
import Head from "next/head";
import { gql, useSubscription } from "@apollo/client";

const CAMPAIGN_SUBSCRIPTION = gql`
  fragment PlayerFragment on Player {
    id
    playerName
    characterName
    isGM
    inspiration
  }

  fragment CampaignFragment on Campaign {
    id
    name
    gmInspiration
    players {
      ...PlayerFragment
    }
  }

  subscription CampaignSubscription($id: ID!) {
    campaign(id: $id) {
      ...CampaignFragment
    }
  }
`;

const Home: NextPage = () => {
  const { data, loading, error } = useSubscription(CAMPAIGN_SUBSCRIPTION, {
    variables: {
      id: 1,
    },
  });

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <pre>
          <code>{JSON.stringify({ data, loading, error }, undefined, 2)}</code>
        </pre>
      </main>
    </div>
  );
};

export default Home;
